---
title: "CNN vs. Onion"
---

This repository contains two complementary classroom activities designed to introduce students to Bayesian and Frequentist approaches to reasoning under uncertainty. Each activity includes detailed facilitator guides, student materials, and R-based exercises for data exploration and model interpretation.

Each activity is designed for classroom use with built-in flexibility for guided instruction or independent exploration. Facilitator guides provide setup instructions, discussion prompts, and example code.

## Bayesian Activity: CNN vs. The Onion – Modeling Prior and Posterior Beliefs

The goal of this activity is to explore how prior beliefs, what we think is probable before seeing any data, can influence the conclusions we draw after seeing new evidence (our posterior beliefs).

Before taking the CNN vs The Onion headline quiz, students are encouraged to think about how many headlines they expect a person might guess correctly and turn that guess into a *prior model*, or starting point for their beliefs. Students take the short quiz distinguishing real headlines (CNN) from satirical ones (The Onion), and update their *prior model* using quiz data to form a *posterior model*. Student compare three different prior models representing other beliefs about how many answers people will get correct in the game: someone expecting a person to guess most answers correctly (optimistic), someone undecided (no prior knowledge) about whether a person will guess many right or wrong (undecided), and someone expecting to guess most answers incorrectly (pessimistic).

### Learning Objectives:

- Construct and interpret prior and posterior models

- Visualize model updates with new data

- Calculate and compare summary statistics (mean, mode, standard deviation)

### Activity Resources

- [Classroom Activity](bayesian-activity/cnn-onion-beta-binomial.qmd)

- [Facilitator Guide](bayesian-activity/cnn-onion-facilitator-guide.qmd)

- [Student Handout](bayesian-activity/cnn-onion-student-handout.qmd)

## Frequentist Activity: Hypothesis Testing with “CNN vs. The Onion” Quiz Data

In this activity, students use their quiz results to practice Frequentist reasoning. They simulate data, review distributions, and conduct both informal and formal hypothesis tests to assess their ability to distinguish real versus fake news headlines.

### Learning Objectives:

- Review probability distributions and sampling variability

- Use R to simulate data and compute test statistics

- Perform informal and formal hypothesis testing


### Activity Resources

- [Student Handout](frequentist-activity/cnn-onion-template.qmd)



## Acknowledgements

This work was supported by the National Science Foundation under Grant Nos #2215879, #2215920, and #2215709